---
version: "2.0"

services:
  dbms:
    build:
      context: .
      dockerfile: postgresql/Dockerfile
      args:
        IRODS_RESOURCES: "$IRODS_RES_CONF_NAME:$IRODS_CONF_HOST:$IRODS_VAULT"
        IRODS_ZONE_NAME: "$IRODS_ZONE_NAME"
        DB_NAME: "$DB_NAME"
        DB_USER: "$DB_USER"
        DB_PASSWORD: "$DB_PASSWORD"
        DBMS_PORT: "$DBMS_PORT"
        IRODS_ADMIN_USER: "$IRODS_ADMIN_USER"
        IRODS_ADMIN_PASSWORD: "$IRODS_ADMIN_PASSWORD"
    image: cyverse/irods-test-postgres

  irods:
    build:
      context: .
      dockerfile: "irods_$IRODS_VER/Dockerfile"
      args:
        DB_NAME: "$DB_NAME"
        DB_USER: "$DB_USER"
        DB_PASSWORD: "$DB_PASSWORD"
        DBMS_HOST: "$DBMS_HOST"
        DBMS_PORT: "$DBMS_PORT"
        DBMS_TYPE: "$DBMS_TYPE"
        IRODS_CONTROL_PLANE_KEY: "$IRODS_CONTROL_PLANE_KEY"
        IRODS_CONTROL_PLANE_PORT: "$IRODS_CONTROL_PLANE_PORT"
        IRODS_DEFAULT_RESOURCE: "$IRODS_DEFAULT_RESOURCE"
        IRODS_FIRST_EPHEMERAL_PORT: "$IRODS_FIRST_EPHEMERAL_PORT"
        IRODS_LAST_EPHEMERAL_PORT: "$IRODS_LAST_EPHEMERAL_PORT"
        IRODS_HOST: "$IRODS_CONF_HOST"
        IRODS_NEGOTIATION_KEY: "$IRODS_NEGOTIATION_KEY"
        IRODS_SCHEMA_VALIDATION: "$IRODS_SCHEMA_VALIDATION"
        IRODS_SYSTEM_GROUP: "$IRODS_SYSTEM_GROUP"
        IRODS_SYSTEM_USER: "$IRODS_SYSTEM_USER"
        IRODS_ZONE_NAME: "$IRODS_ZONE_NAME"
        IRODS_ZONE_KEY: "$IRODS_ZONE_KEY"
        IRODS_ZONE_PORT: "$IRODS_ZONE_PORT"
        IRODS_ADMIN_USER: "$IRODS_ADMIN_USER"
        IRODS_ADMIN_PASSWORD: "$IRODS_ADMIN_PASSWORD"
    image: "cyverse/irods-test:v$IRODS_VER"
    hostname: "$IRODS_CONF_HOST"
    ports:
      - "1247:1247"
      - "$IRODS_FIRST_EPHEMERAL_PORT-$IRODS_LAST_EPHEMERAL_PORT:$IRODS_FIRST_EPHEMERAL_PORT-$IRODS_LAST_EPHEMERAL_PORT"
    depends_on:
      - dbms
  